spring.application.name=urlshortener
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=8080
app.base-url=http://localhost:8080

spring.data.redis.host=localhost
spring.data.redis.port=6379

app.jwt.secret=3f8a2b1c9d7e6f4a5b0c8d2e1f9a7b3c4d5e6f0a1b2c3d4e5f6a7b8c9d0e1f2a
app.jwt.expiration=86400000

#app.base-url=https://nano-link-production.up.railway.app